### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by berndhahnebach** [ifcquery/ifcplusplus#109]
Hi Fabian,

build instructions for Linux are totally outdated here ... https://github.com/ifcquery/ifcplusplus/wiki/Build-instructions

Newer informations are provided in README in my repo which will compile on Debian Stretch
https://github.com/berndhahnebach/ifcplusplus/blame/master/README.md#L1-L27

bernd

**Comment by ifcquery** [comment]
Hi Bernd,

ok, can I just set a link to
https://gist.github.com/berndhahnebach/e4d57634fe7eebbae537bf3da1b1b95a
in https://github.com/ifcquery/ifcplusplus/wiki/Build-instructions
instead of explicit instructions? I can't maintain them anyway.

Cheers,
Fabian


---------------------------------------------
Fabian Gerold
Mail: fabian.gerold@gmail.com
Phone: (+49)176 55119954


Am Mi., 22. Aug. 2018 um 22:55 Uhr schrieb Bernd Hahnebach <
notifications@github.com>:

**Comment by berndhahnebach** [comment]
Hi Fabian,

yes this seams a good idea. Furthermore a link to the README of my repo would be a good idea. In there are a few more informations. See https://github.com/berndhahnebach/ifcplusplus/blob/master/README.md

cheers bernd

BTW. ATM ifcplusplus

**Comment by mfvescovi** [comment]
Hey @ifcquery and @berndhahnebach ,
I'm interested in packaging ifcplusplus officially for Debian (being a DD myself).
Could it be possible to work on an actual release of ifc++ instead of a git snapshot?
That would help a lot.

TIA.
