### ISSUE TITLE
differences with IfcOpenShell

### ISSUE THREAD

**Issue by promethe42** [ifcquery/ifcplusplus#125]
Hi,

I'm studying a possible integration of your library to read IFC models in our app.
I just tested your viewer app on Windows and I have to admit I'm very positively impressed.
I get better results than what I get with IfcOpenShell:

* some objects that are missing in IfcOpenShell render perfectly in your viewer
* the loading performance is >10x faster in some cases

Yet IfcOpenShell is a quite mature project...

So I have to ask do you know IfcOpenShell and how do you explain such differences?
I understand ifcplusplus supports only IFC 4 Add2: does that mean *all* of the spec is supported?

Thank you for your answers!

**Comment by ifcquery** [comment]
Hi, 
I don't know IfcOpenShell very good, but as far as I know it uses late binding for accessing IFC objects.
IFC++ uses early binding, so all IFC objects are loaded with all attributes into a fully linked class model, that can be accessed very fast.

IfcOpenShell uses OpenCascade for geometric operations. OCC has lots of features, but boolean operations are really slow.
IFC++ uses Carve as geometric model and for boolean operations. Carve is very fast, but has only polygons for lines and face boundaries. So for example, a curve segment with radius will be converted into a polygon with n edges. For visualization, that is normally fine since the GPU also knows only lines and triangles. For some purposes, the loss of information (for example radius) might be a problem.
In IFC++ there is also a geometric modeller for OCC, that I implemented for a customer. But it is not complete yet.

For IFC4 Add2, all classes are supported, since the class model is generated from the official schema. The most important geometric representations are implemented, but some are missing yet. Those I can implement for customers upon request.

**Comment by promethe42** [comment]
Thank you for your answers.

I will test further.

> Those I can implement for customers upon request.

We will definitely consider it when needed.
