### ISSUE TITLE
OCCT Geometry Build Broken

### ISSUE THREAD

**Issue by clanzotti** [ifcquery/ifcplusplus#66]
Hi Fabian,

first, my compliments for your good work.

I want let you know that:

When compiling to use OCCT geometry build errors came in. There are calls in GeometryInputData.h to  an undefined applyPosition() function (should it be applyPositionItem?). SolidModelConverter.h have some errors like an undefined vec_item_data (maybe it was item_data that you wanted to use and call addItemData() on it?). 

I'm trying to check the OCCT geometry as CARVE on some models do not generate correct normals and also materials color are not always correct. 

For an example you can check this: http://openifcmodel.cs.auckland.ac.nz/_models/030811DuplexModel-IFC-2011-05-05.zip 

There the sofa inside the building should be red and the table should be light brown (to name a few). Flipped normals (or bad geometry) can be seen also. 

Thanks.

Carlo

**Comment by ifcquery** [comment]
Hi Carlo,
OCCT geometry should work now.  It is only experimental, normally I use Carve, because it is a lot faster.
Sometimes on open shells, the normals are flipped, because in IFC only the triangles are defined, not the normals. In OpenSceneGraph you can set the osg::LightModel to setTwoSided( true ), then the flipped normals are not such a big problem.
In the model that you mentioned, the sofa has actually no color defined.  It is possible that not all colors come through IFC++ correctly. If you have a color definition in an IFC model, that does not show up in IFC++, please let me know :)

Cheers,
Fabian
