### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by boulabiar** [ifcquery/ifcplusplus#95]
Hi,

I can't find any documentation or examples on how to use this project.
Can you add a section in the ReadMe.md on how to start a simple project using simple CRUD api to modify a file?

Thanks

**Comment by ifcquery** [comment]
Hi,
there is a "SimpleViewerExample" application in the project. If you downloaded the repository, you already have it. Just debug the application, and you will see how it works.
Beyond that, there is professional support available. For that, please refer to http://www.ifcquery.com/

Thanks

**Comment by alejandronespereira** [comment]
The Simple Viewer example can't start to pass as documentation. Could we get some simple cases about how to read a file, extract the different objects, etc? 
I have contacted the mail at the www.ifcquery.com a week ago but I am still waiting for an answer

**Comment by myl-prog** [comment]
I've been interested in manipulating ifc files through other languages for a few days and I came across ifcplusplus , I have the same problem , installing openscenegraph seems to be impossible, and if I understand correctly , the simple viewer should do the trick , and it does , but I still don't know how to use the library exactly in order to manipulate the ifc files . I'd really appreciate having any sort of support , thank you in advance .

**Comment by ifcquery** [comment]
You can not manipulate the file actually. Instead, IFC++ reads the file and converts it into a tree of objects, according to the building structure that you can also see in the SimpleViewerExample.
Objects then can be manipulated like any C++ object. The changed object model can then be written to a file. All these steps are in the SimpleViewerExample, just debug and see how it works.
If you want a specific functionality like adding a wall with windows and local coordinate system, merging or converting models etc, that can be implemented through professional support on www.ifcquery.com
